# Generated by Django 5.1.1 on 2024-12-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litestripe', '0003_alter_orphanedpayment_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=512)),
                ('client_reference_id', models.CharField(max_length=1024)),
                ('stripe_subscription_id', models.CharField(max_length=512)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('cancel_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(max_length=256)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
