# Generated by Django 5.1.1 on 2024-12-15 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litestripe', '0004_stripesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanedpayment',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 15, 18, 35, 4, 825443, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orphanedpayment',
            name='dt_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
